# Generated by Django 4.1.1 on 2022-10-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bycycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_mark', models.CharField(max_length=20, verbose_name='марка')),
                ('b_model', models.CharField(max_length=30, verbose_name='модель')),
                ('price', models.FloatField(verbose_name='цена')),
                ('b_color', models.CharField(max_length=20, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Список велосипедов',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Список продукт'},
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
