# Generated by Django 4.1.1 on 2022-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bycycle_alter_products_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_mark', models.CharField(max_length=20, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
                ('color', models.CharField(max_length=20, verbose_name='цвет')),
                ('made_in', models.CharField(max_length=30, verbose_name='сделано в')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Список часов',
            },
        ),
    ]
